### ISSUE TITLE
Need more details

### ISSUE THREAD

**Issue by Ayyarappan** [MarioIannotta/ShyView#1]
I'm not able to hide entire screen view, while adding a view as shyView.
Need more explanation about the setup and usage.
Thanks.

**Comment by MarioIannotta** [comment]
Hello there!
This components is a UIView subclass that hides his subview (provided in the init) when the user takes a screenshot / records a video.

If you want to hide the entire screen, you need to wrap the entire screen in a view. 
eg: `ShyView(entireScreenView)`.

However I imagine this is not always straightforward so my suggestion is to wrap only the “real sensitive” components in different ShyViews.

You can check-out the example folder to see the code of the Demo gif.
